title: अल्फाफोल्ड - एक प्रैक्टिकल गाइड
description: यह ट्यूटोरियल उन रिसर्चर्स के लिए है जो प्रोटीन स्ट्रक्चर का अनुमान लगाने के लिए AlphaFold का इस्तेमाल करने और इन अनुमानों को अपने प्रोजेक्ट्स में शामिल करने में दिलचस्पी रखते हैं।

baseurl: ""
url: "https://sandykadam.github.io/AlphaFold-A-practical-guide"

markdown: kramdown
theme: null

permalink: pretty

# Build settings
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules

# Collections (optional if needed later)
collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
