backend:
  name: github
  repo: bioinfocommunity/alphafold-a-practical-guide
  branch: main
  base_url: https://api.netlify.com
  auth_endpoint: /auth
  # You’ll use GitHub authentication via OAuth app (see step 3)

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "courses"
    label: "Course Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
