backend:
  name: github
  repo: bioinfocommunity/AlphaFold-A-practical-guide
  branch: main
  auth_type: implicit
  client_id: Ov23li1qSOgUfvTg2G60
  base_url: https://github.com
  # You’ll use GitHub authentication via OAuth app (see step 3)

media_folder: "assets/uploads"
public_folder: "/uploads"

collections:
  - name: "courses"
    label: "Course Content"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
