<html lang="en" dir="ltr">

<head>
	<meta charset="utf-8" />
	<title>AlphaFold | EMBL-EBI Training</title>
	<link rel="stylesheet" href="https://assets.emblstatic.net/vf/v2.5.25/css/styles.css" type="text/css">

	<link rel="stylesheet" href="https://ebi.emblstatic.net/web_guidelines/EBI-Icon-fonts/v1.3/fonts.css" type="text/css"
		media="all" />
	<style>
	#ebi-hero-background {
		background-image: url('https://acxngcvroo.cloudimg.io/v7/www.embl.org/files/wp-content/uploads/Online-tutorial.jpg');
		background-repeat: no-repeat;
		background-size: cover;
	}
	</style>
</head>
<body class="vf-body">
	<div class="dialog-off-canvas-main-canvas" data-off-canvas-main-canvas>
		<span data-protection-message-disable="true"></span>
		<header id="masthead-black-bar" class="clearfix masthead-black-bar | ebi-header-footer vf-content vf-u-fullbleed">
		</header>
		<div class="layout-container">
			<main class="page-content clearfix" role="main">
				<div class="visually-hidden">
					<a id="main-content" tabindex="-1">
					</a>
				</div>
				<div class="vf-content">
					<div>
						<div id="block-ebi-academy-content--89">
							<div id="ebi-hero-background" style="">
								<div class="vf-body">
									<section class="vf-hero | vf-u-fullbleed" style="background:none;">
										<div class="vf-hero__content | vf-box | vf-stack vf-stack--400" style="min-width:350px">
											<p class="vf-hero__kicker" style="text-transform:uppercase">Tutorial en línea</p>
											<h2 id="course_title" class="vf-hero__heading">AlphaFold</h2>
											<p class="vf-hero__subheading">Una guía práctica</p>
										</div>
									</section>
								</div>
							</div>
							<article data-history-node-id="2555" role="article">
								<div data-history-node-id="2555" role="article">
									<div class="vf-body published">
										<div class="vf-u-margin__top--500"></div>
										<section class="embl-grid">
											<div class="embl-training__sidebar">
												<div class="vf-u-margin__top--500"></div>
												<figure class="vf-figure ebi-academy-book-cover-image">

													<img class="vf-figure__image"
														src="//trainingcontent.embl.org/sites/default/files/book-images/AlphaFold.png" alt="">

												</figure>
												<div class="vf-u-margin__top--500"></div>
												<p class="vf-u-type__text-body--3 vf-u-margin--0">
													Tiempo para completar: </p>
												<p class="vf-u-type__text-body--3 vf-u-margin--0">3 horas</p>
												</p>
												<hr class="vf-divider vf-u-margin__bottom-md">
												<p class="vf-u-type__text-body--3 vf-u-margin--0 vf-u-margin__bottom--xs">
													Escrito por:</p>
												<div class="vf-u-margin__top--100"></div>
												<ul class="vf-list vf-list--compact vf-u-margin__bottom-md">
													<li class="vf-list__item ">
														<a class="vf-link vf-link--primary vf-u-type__text-body--3 "
															href=https://www.ebi.ac.uk/people/person/paulyna-gabriela-magana-gomez> Paulyna Gabriela
															Magana Gomez </a>
													</li>
													<li class="vf-list__item ">
														<a class="vf-link vf-link--primary vf-u-type__text-body--3 "
															href=https://www.ebi.ac.uk/training/trainers/oleg-kovalevskiy> Oleg Kovalevskiy </a>
													</li>
												</ul>
												<p class="vf-u-type__text-body--3 vf-u-margin--0 vf-u-margin__bottom--xs">
													Traducido por:</p>
												<div class="vf-u-margin__top--100"></div>
												<ul class="vf-list vf-list--compact vf-u-margin__bottom-md">
													<li class="vf-list__item ">
														Translator 1
													</li>
													<li class="vf-list__item ">
														Translator 2
													</li>
												</ul>
												<p class="vf-u-type__text-body--3 vf-u-margin--0 vf-u-margin__bottom-md">
													traducido el: Octubre de 2025</p>
												</p>
												<p class="vf-u-type__text-body--3 vf-u-margin--0 vf-u-margin__bottom-md">
													Última revisión: Junio ​​de 2025</p>
												</p>
												<div class="vf-u-margin__top--500"></div>
												<hr class="vf-divider vf-u-margin__bottom-md">
												<!-- Navigation -->
												<nav>
												  <ul class="vf-tree__list  vf-tree__list--1 | vf-list">
												  <li class="vf-tree__item">
												  <a class="vf-tree__link" href="/AlphaFold-A-practical-guide">Course overview</a>
												    {% comment %}
												      Get only markdown files (exclude README.md)
												    {% endcomment %}
												    {% assign markdown_pages = site.pages | where_exp: "p", "p.path contains '.md'" %}
												    {% assign filtered_pages = markdown_pages | where_exp: "p", "p.name != 'README.md'" | sort: "path" %}
												
												    {% comment %}
												      Group pages by their top-level directory
												    {% endcomment %}
												    {% assign grouped_pages = filtered_pages | group_by_exp: "p", "p.path | split: '/' | first" %}
												
												    {% for group in grouped_pages %}
												      {% assign folder = group.name %}
												      {% assign folder_pages = group.items %}
												
												      {% comment %}
												        Skip root-level files (those not inside a folder)
												      {% endcomment %}
												      {% if folder contains '.' %}
												        {% comment %}
												          Clean folder name — remove leading numbers and format to sentence case
												        {% endcomment %}
												        {% assign folder_clean = folder 
												          | replace: '_', ' ' 
												          | replace: '-', ' ' 
												          | split: '.' 
												          | last 
												          | strip 
												        %}
												
												        {% comment %}
												          Find index.md in this folder
												        {% endcomment %}
												        {% assign index_page = folder_pages | where: "name", "index.md" | first %}
												
												        <li class="vf-tree__item">
												          {% if index_page %}
												            <a class="vf-tree__link" href="{{ index_page.url | relative_url }}">
												              {{ index_page.title | default: folder_clean | capitalize }}
												            </a>
												          {% else %}
												            {{ folder_clean | capitalize }}
												          {% endif %}
												
												          {% comment %}
												            Render subpages inside folder (excluding index.md)
												          {% endcomment %}
												          <ul class="vf-tree__list  vf-tree__list--1 | vf-list" style="margin-left: 16px">
												            {% assign subpages = folder_pages 
												              | where_exp: "p", "p.name != 'index.md'" 
												              | where_exp: "p", "p.name != 'README.md'" 
												              | sort: "path" 
												            %}
												            {% for sub in subpages %}
												              {% assign name_clean = sub.name 
												                | replace: '.md', '' 
												                | split: '.' 
												                | last 
												                | replace: '-', ' ' 
												                | strip 
												              %}
												              <li class="vf-tree__item">
												                <a class="vf-tree__link" href="{{ sub.url | relative_url }}">
												                  {{ sub.title | default: name_clean | capitalize }}
												                </a>
												              </li>
												            {% endfor %}
												          </ul>
												        </li>
												      {% endif %}
												    {% endfor %}
												  </ul>
												</nav>



												<hr class="vf-divider vf-u-margin__bottom-md">
												<p>
													<a href="https://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons"
															src="http://trainingcontent.embl.org/themes/custom/ebi_academy/images/CC_BY.png"
															style="width: 125px; height: 44px;" width="125" height="44"></a>
												</p>
												<p class="vf-u-type__text-body--3">Todos los materiales son obras culturales gratuitas con licencia Creative Commons.
													<a href="https://creativecommons.org/licenses/by/4.0/"
														class="vf-link vf-link--primary  vf-u-margin--0" style="display:inline">Licencia Atribución 4.0 Internacional (CC BY 4.0), excepto cuando se proporcionen más detalles de la licencia </a>
												</p>
												<div class="vf-u-margin__top--500"></div>
												<hr class="vf-divider vf-u-margin__bottom-md">

												
											</div>
											<!-- Sidebar end -->
											<div class="acc">
												<div class="vf-u-margin__top--500"></div>
												{{ content }}


											</div>
										</section>
									</div>
								</div>
							</article>



						</div>
					</div>
				</div>
			</main>
  <script src="https://assets.emblstatic.net/vf/v2.5.25/scripts/scripts.js"></script>
		</div>

	</div>

</body>

</html>
