name: Deploy GitHub Pages for Multiple Branches

on:
  push:
    branches:
      - main
      - -es
      - -fr
      - -de

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repo
      - uses: actions/checkout@v4

      # Step 2: Determine deploy folder based on branch
      - name: Set deploy folder
        id: set_folder
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          if [ "${GITHUB_REF##*/}" = "main" ]; then
            echo "DEPLOY_DIR=dist" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" = "-es" ]; then
            echo "DEPLOY_DIR=dist/es" >> $GITHUB_ENV
          elif [ "${GITHUB_REF##*/}" = "-fr" ]; then
            echo "DEPLOY_DIR=dist/fr" >> $GITHUB_ENV
          else
            echo "DEPLOY_DIR=dist/other" >> $GITHUB_ENV
          fi

      # Step 3: Prepare build (if you have static files)
      - name: Copy content to deploy folder
        run: |
          mkdir -p $DEPLOY_DIR
          cp -r * $DEPLOY_DIR
          # Optional: remove workflow file from deploy
          rm -f $DEPLOY_DIR/.github/workflows/gh-pages.yml

      # Step 4: Deploy to gh-pages branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ${{ env.DEPLOY_DIR }}
          keep_files: true
